name: Publish Flutterbot Common NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Flutterbot.Common.csproj --configuration Release --no-restore
    - name: Pack package
      run: dotnet pack Flutterbot.Common.csproj --configuration Release --version-suffix ${{ github.run_number }} --no-build --include-symbols -o ~/build/nuget
    - name: Prep packages
      run: dotnet nuget add source --username 99williamsdav --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/99williamsdav/index.json"
    - name: Publish NuGet package to GitHub
      run: dotnet nuget push ~/build/nuget/*.nupkg  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
